### PR TITLE
Solved Issue - Robot does not stop on key release

### PR DESCRIPTION
**Pull request by Chris177**
Besides fixing this issue I solved a problem that some older teleop_keyboard codes had that was sending unnecessary stop messages to cmd_vel, so now it's possible to use this teleop withother nodesc that also publishes to cmd_vel

### CODE REVIEW

**Comment by trainman419** [comment]
I see several major flaws in this implementation:
* It doesn't have any knowledge of the key repeat rate, so there's no way to know if the timeouts are set correctly or not
* Blocking the outer program loop by spinning in an inner loop and using delays for debouncing delays or prevents processing of other incoming key events, and it looks like keypresses may be lost.
* To the best of my knowledge, the current version works reasonably well with muxes because it only publishes a message on key events. I don't see how this behavior has changed
* The "ramp to 0" functionality isn't configurable, which means on very large or small robot it will be tuned incorrectly and will cause undesired behavior, and the quadratic ramp that you've implemented will cause a lot of stress on large drivetrains. Please reimplement this as a linear ramp with configurable acceleration.
* The "ramp to 0" functionality blocks all incoming keypresses and makes it impossible to abort the deceleration or decelerate more quickly; for a large robot this could cause physical damage. Please reimplement this without using blocking inner loops. This could probably be done more cleanly with a state machine.

**Comment by Chris177** [comment]
Ok, 
I'll fix this probably next week, because I don't have much time right now.

The key repeat rate I don't know if it matters, because if there is something to read using the function select.select() it will read, if not it will return empty, so I just need to compare to see if something is being pressed.

The loops I agree they are a problem, and I must allow other key events while moving the robot, I'll fix this.

The current version don't implement any kind of acceleration, it just allow to turn the speed up or down by 10%, So should I add an acceleration control, or just use a linear ramp to go to zero, like decrease 10% the speed on each loop, then should I use some timeout inside those loops? Because there should be a way to decrease smoothly the speed to zero

**Comment by Chris177** [comment]
I found that there might be some issues to implement that.
The way the keys are being read might be a problem for multiple keys being pressed at the same time. When I'm pressing some key and then start pressing another I read a stream of presses and releases for the new key but no more events fore the older one. So I can't change the speed while I'm controlling the robot direction.

 To handle multiple key pressing the easiest way is to use something like pygame, but then I don't know if the keyboard teleop should depend on an external library...

So I consider 3 options:
1. Leave the way it is, where the robot don't stop or change behavior unless other key is pressed. It is possible to change the speed while it is moving, because no other key is being pressed at the same time.
2. Use my implementation, just fixing the loops and the ramp to zero. The robot will stop on key releases, but it won't be possible to change its speed while it is moving. An acceleration ramp might be implemented as well to make it go to the desired speed smoothly  
3. Use another library for reading key events, making it possible to read multiple key inputs at the same time and fixing all the issues that we have

**Comment by trainman419** [comment]
Implemented in #24 and released to Kinetic, Melodic and Noetic as version 1.0.0 (  https://github.com/ros/rosdistro/pull/25604, https://github.com/ros/rosdistro/pull/25607, https://github.com/ros/rosdistro/pull/25608 )

**Pull request closed without merging**
