### PR TITLE
Added launch file, updated readme

### PR DESCRIPTION
**Pull request by theroboticsheep**

### CODE REVIEW

**Comment by trainman419** [comment]
Two comments:

 1. Please don't update the version number or the changelog. I will do that as part of the release process
 2. I don't see the need for a launch file.

**Comment by trainman419** [comment]
Do you have any response to my comments?

If I haven't heard back within a week, I will close this PR.

**Comment by theroboticsheep** [comment]
Sorry, didn't realize you were waiting for feedback. 
1.  My bad. Wasn't sure the standard protocol. 
2.  I find the launch file useful so I can launch teleop with a single command without having to worry about starting roscore. In retrospect, I realize that's a rare case.

**Comment by trainman419** [comment]
Replaced by #5

**Pull request closed without merging**
