### PR TITLE
Correct exception handling; Python3 print compatible

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
ping :)

**Comment by trainman419** [comment]
This doesn't look like it's Python 2 compatible, and since Python 2 is still the default version of python for ROS and most Linux distributions, that makes it difficult to merge.

I _think_ the only fix for this should be to import the print function from future.

**Comment by MatthijsBurgh** [comment]
@trainman419, applied import print from future.

**Comment by MatthijsBurgh** [comment]
ping again :)

**Comment by MatthijsBurgh** [comment]
Ping

**Comment by trainman419** [comment]
I've confirmed that this still works on Python 2.

**Pull request merged**
